"use client"
import { Area, AreaChart, CartesianGrid, XAxis, YAxis } from "recharts"
import { ChartContainer, type ChartConfig } from "@/components/ui/chart"
import { cn } from "@/lib/utils"
const data=[{m:"Jan",a:70,b:42,c:85},{m:"Feb",a:82,b:55,c:95},{m:"Mar",a:60,b:45,c:75},{m:"Apr",a:90,b:68,c:110},{m:"May",a:72,b:50,c:88},{m:"Jun",a:96,b:65,c:105},{m:"Jul",a:84,b:72,c:92},{m:"Aug",a:100,b:58,c:115},{m:"Sep",a:78,b:48,c:102}] as const
const config={a:{label:"2024",color:"var(--chart-4)"},b:{label:"2025",color:"var(--chart-2)"},c:{label:"2026",color:"var(--chart-1)"}} satisfies ChartConfig
export function RevenueForecastLineChart({className}:{className?:string}){return <section data-slot="revenue-forecast-line-chart" className={cn("w-full rounded-xl bg-card text-card-foreground shadow-sm ring-1 ring-foreground/10",className)} style={{height:"520px",padding:"30px"}}><header className="flex items-center justify-between"><div className="flex items-center" style={{gap:"16px"}}><span className="flex items-center justify-center rounded-xl bg-primary/10 text-primary" style={{width:"54px",height:"54px"}}>↗</span><div><h2 className="text-xl leading-7 font-semibold">Revenue Forecast</h2><p className="m-0 text-base text-muted-foreground">Overview of Profit</p></div></div><div className="flex" style={{gap:"14px"}}><Legend c="var(--chart-4)" t="2024"/><Legend c="var(--chart-2)" t="2025"/><Legend c="var(--chart-1)" t="2026"/></div></header><ChartContainer config={config} className="w-full" style={{height:"360px",aspectRatio:"auto",marginTop:"28px"}} initialDimension={{width:744,height:360}}><AreaChart data={data} margin={{top:8,right:0,left:0,bottom:12}}><CartesianGrid stroke="var(--border)"/><XAxis dataKey="m" axisLine={false} tickLine={false} tickMargin={15}/><YAxis domain={[0,120]} ticks={[0,20,40,60,80,100,120]} axisLine={false} tickLine={false} width={34}/><Area type="monotone" dataKey="a" stroke="var(--color-a)" fill="var(--color-a)" fillOpacity={.05} strokeWidth={2.5}/><Area type="monotone" dataKey="b" stroke="var(--color-b)" fill="var(--color-b)" fillOpacity={.08} strokeWidth={2.5}/><Area type="monotone" dataKey="c" stroke="var(--color-c)" fill="var(--color-c)" fillOpacity={.1} strokeWidth={2.5}/></AreaChart></ChartContainer></section>}
function Legend({c,t}:{c:string;t:string}){return <span className="flex items-center text-sm text-muted-foreground" style={{gap:"6px"}}><i className="size-2 rounded-full" style={{backgroundColor:c}}/>{t}</span>}
export default RevenueForecastLineChart
